
export const userTypes = {
    USER_START:"USER_START",
    USER_SUCESS:"USER_SUCESS",
    USER_FAIL:"USER_FAIL",
    GET_USER_START:"GET_USER_START",
    GET_USER_SUCCESS:"GET_USER_SUCCESS",
    GET_USER_FAIL:"GET_USER_FAIL",
    LOGOUT:"LOGOUT",
    UPDATE_USER_START:"UPDATE_USER_START",
    UPDATE_USER_SUCESS:"UPDATE_USER_SUCESS",
    UPDATE_USER_FAIL:"UPDATE_USER_FAIL",
}
